### ISSUE TITLE
Error response from daemon: client version 1.43 is too new. Maximum supported API version is 1.41

### ISSUE THREAD

**Issue by savvasdalkitsis** [nightlord189/docklogkeeper#4]
I get the above message when deploying the app. 

No containers show in the list

**Comment by nightlord189** [comment]
I suppose, it's because version of used docker library (github.com/docker/docker) is 24.0.5. Could you try to upgrade docker?

**Comment by tymmej** [comment]
You can add `DOCKER_API_VERSION=1.41` to docker environment.
Works for me.
