### ISSUE TITLE
Huge CPU usage

### ISSUE THREAD

**Issue by tymmej** [nightlord189/docklogkeeper#6]
You can clearly see moment I added docklogkeeper - 2023.09.03 ~9:00.

CPU usage was under dockerd process, container usage was under 1%. After turning off container CPU usage dropped to normal values.

<img width="1459" alt="image" src="https://github.com/nightlord189/docklogkeeper/assets/443698/f3d90787-97ad-4310-8da6-86f3e0e0fcba">

**Comment by nightlord189** [comment]
How many containers do you have running on your system? And how many logs they generated?

**Comment by nightlord189** [comment]
@tymmej, could you try image nightlord189/docklogkeeper:follow ? I have changed method of getting daemon logs to follow. It can reduce CPU usage.

**Comment by tymmej** [comment]
Sorry for late responce, I was on vacation.

1) I have about ~20 containers, I don't know how many logs they generate - is it easy option to check it?
2) I've updated image, it looks better now (no visible increase in CPU usage above base level) :+1:

**Comment by nightlord189** [comment]
@tymmej, Yes, i have changed extracting logs method in last version. I think this problem is fixed now.
